WS2812_DRIVER = vendor
DYNAMIC_TAPPING_TERM_ENABLE = yes

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += gc9a01_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = yes

SRC += usaani.qgf.c
SRC += fn.qgf.c

ENCODER_ENABLE = yes

DEBOUNCE_TYPE = sym_eager_pk
